[package]
name = "rust_from_python"
version = "0.1.0"
authors = ["tropxy <andre.duarte@mobilityhouse.com>"]
edition = "2018"

[lib]
name = "string_sum"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.11.1"
features = ["extension-module"]
